### ISSUE TITLE
Nice_table: Significance Asterisks for p value

### ISSUE THREAD

**Issue by TinaYibingChen** [rempsyc/rempsyc#25]
Hi, I am really appreciate your rempsyc package.
I have a small request regarding the notation used for p-values in the table. Are there any way to modify the legend for significance levels from "* p < .05, ** p < .01, *** p < .001" to "* p < 0.1, ** p < 0.05, *** p < 0.01"? 
Thank you so much !!!

**Comment by rempsyc** [comment]
No, this is not possible. The current values reflect APA recommandations which is the style I try to follow. I don't think it is worth to add a feature to change significance levels because it would be quite complicated to accommodate all possible thresholds with I fear little benefit in comparison. So this would need to be adjusted manually.
